from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from view import (
    add_comment,
    add_ingredient_page,
    add_recipe_page,
    add_technique_page,
    comment_dislike_toggle,
    comment_like_toggle,
    culinary_compare_page,
    culinary_road_page,
    edit_entry,
    entry_page,
    index,
    ingredient_detail_page,
    ingredients_page,
    login_page,
    logout_view,
    profile_page,
    proposal_decide,
    proposals_inbox,
    recipe_detail_page,
    recipe_like_toggle,
    recipes_page,
    register_page,
    report_action,
    reports_inbox,
    search_page,
    submit_report,
    technique_detail_page,
    techniques_page,
)

urlpatterns = [
    path('', index),
    path('login/', login_page),
    path('logout/', logout_view),
    path('register/', register_page),
    path('entry/', entry_page),
    path('culinary-road/', culinary_road_page),
    path('culinary-compare/', culinary_compare_page),
    path('profile/', profile_page),
    path('recipes/', recipes_page),
    path('recipes/add/', add_recipe_page),
    path('recipes/<int:pk>/', recipe_detail_page),
    path('recipes/<int:pk>/like/', recipe_like_toggle),
    path('techniques/', techniques_page),
    path('techniques/add/', add_technique_page),
    path('techniques/<int:pk>/', technique_detail_page),
    path('ingredients/', ingredients_page),
    path('ingredients/add/', add_ingredient_page),
    path('ingredients/<int:pk>/', ingredient_detail_page),
    path('search/', search_page),
    path('comments/<str:kind>/<int:pk>/add/', add_comment),
    path('comments/<int:pk>/like/', comment_like_toggle),
    path('comments/<int:pk>/dislike/', comment_dislike_toggle),
    path('<str:kind>s/<int:pk>/edit/', edit_entry),
    path('proposals/', proposals_inbox),
    path('proposals/<int:pk>/decide/', proposal_decide),
    path('reports/<str:kind>/<int:pk>/submit/', submit_report),
    path('reports/', reports_inbox),
    path('reports/<int:pk>/action/', report_action),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
