# Generated by Django 6.0.3 on 2026-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(default=30, help_text='Minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
