# Generated by Django 6.0.3 on 2026-04-13 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='core.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technique',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='techniques', to='core.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='technique',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='technique',
            unique_together={('name', 'region')},
        ),
    ]
