# Generated by Django 6.0.3 on 2026-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ingredient_region_technique_region_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='technique',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='regions',
            field=models.ManyToManyField(related_name='ingredients', to='core.region'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='regions',
            field=models.ManyToManyField(related_name='recipes', to='core.region'),
        ),
        migrations.AddField(
            model_name='technique',
            name='regions',
            field=models.ManyToManyField(related_name='techniques', to='core.region'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='region',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='region',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='region',
        ),
    ]
