# Generated by Django 6.0.3 on 2026-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='core.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='core.technique'),
        ),
    ]
