# Generated by Django 6.0.3 on 2026-04-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recipe_ingredients_recipe_techniques'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cultural_significance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cultural_significance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='technique',
            name='cultural_significance',
            field=models.TextField(blank=True, default=''),
        ),
    ]
