# Generated by Django 6.0.3 on 2026-05-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ingredient_cultural_significance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
