# Generated by Django 6.0.3 on 2026-05-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='necessary_tools',
            field=models.TextField(blank=True, default=''),
        ),
    ]
